### ISSUE TITLE
Graph display overlays block editor

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#153]
When I open the block editor and put it over the stage, any graph displayed on the stage appears in front of the block editor.

**Comment by jos0003** [comment]
As Snap is quite raster heavy, it would make sense if you can get the graph display to render in canvas also. You can do this by getting d3.js to visualise the graph and canvas to render it in the right drawing order (that would require writing a new visualisation method to draw the nodes and edges though).

**Comment by stevenbird** [comment]
In the absence of a library that supports drawing graphs with Canvas, there is no easy way to fix this.
