### ISSUE TITLE
Help for blocks in the Networks, Edges, Nodes and External tabs

### ISSUE THREAD

**Issue by lottiewilson** [snapapps/edgy#208]
The right-Click help doesn't bring up anything for many of the blocks in the Networks, Edges, Nodes and External tabs. This is a handy feature for beginners, which I was going to point out in beginner tutorials, but it doesn't seem to exist for blocks like 'add node' and 'add edge'. For blocks in other tabs (e.g.'When green flag clicked') right clicking and selecting 'Help' brings up a handy help dialog.

**Comment by stevenbird** [comment]
We need to document the connection between the source filenames and the ultimate help files. A simple way to do this is to create a little shell script as follows:

```
cp "all the nodes - number of nodes.png" help/getNodes.png
cp "all the nodes - number of nodes.png" help/numberOfNodes.png
```
