### ISSUE TITLE
Generating trees of degree 1

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#230]
Balanced trees of degree 1 are always generated with height 1, regardless of the specified depth.

![edgyexample](https://cloud.githubusercontent.com/assets/55406/5768287/7ec74dc6-9d63-11e4-8c73-c4da0e42d98c.png)

**Comment by jarredgallina** [comment]
Being discussed in [this](https://github.com/fkling/JSNetworkX/issues/47) JSNetworkX Issue.

**Comment by jarredgallina** [comment]
Will be resolved in version 3 of JSNetworkX.

**Comment by stevenbird** [comment]
This will be covered in #306.
