### ISSUE TITLE
Blocks to unset a dictionary key and test whether a dictionary key exists

### ISSUE THREAD

**Issue by gregbreese** [snapapps/edgy#234]
There is currently no block to remove a key and its associated value from a dictionary or to test if a given key is in the dictionary.

**Comment by stevenbird** [comment]
Oh, good idea, thanks Greg.

**Comment by jarredgallina** [comment]
Would this only be applicable to the "get all attributes of _" and "set attributes of _ from dict _" blocks? I think that's the only time we use dictionaries. If so, should I tweak the wording to be specific to this case?

**Comment by stevenbird** [comment]
They're on the collections tab.

**Comment by jarredgallina** [comment]
Ah of course, that would explain collections.js. My bad. 
I'll add the two new blocks to that tab.
