### ISSUE TITLE
Priority queue implementation

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#235]
The priority queue support in collections.js needs to support complex objects, with a priority value. E.g. it should be possible to build a priority queue over edges or nodes, and specify which attribute is used for the priority.

**Comment by jarredgallina** [comment]
I think we should specify how I should implement this. 
Should the priority attribute be determined on an object-by-object basis or for the whole pqueue?

If it's object-by-object, I think two new blocks "add node _ to pqueue _ prioritised by _ " and "add edge _ to pqueue _ prioritised by _" will be necessary.

If the entire queue is to be sorted by the same attribute, I think we'll need to have node pqueues and edge pqueues handled by different sets of blocks. 

Thoughts?

**Comment by stevenbird** [comment]
Each object can have its own priority. Can we avoid specifying the type of the object? So we could have `add _ to pqueue _ with priority _`, and also `update _ in pqueue _ to priority _`.
