### ISSUE TITLE
Changing the scaling of blocks using the "zoom blocks" menu option stops Edgy from loading on next launch

### ISSUE THREAD

**Issue by jarredgallina** [snapapps/edgy#240]
This bug effectively kills Edgy for an entire browser. I'm unsure what exactly is going on here, but as a quick fix for now I can remove the option from the menu. I can also add a line to un-break Edgy on browsers that have already encountered the issue.

**Comment by stevenbird** [comment]
It looks like the same issue arose in Snap and was resolved, cf https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/255
