### ISSUE TITLE
Issue with colouring edges

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#244]
The following program creates a graph where some of the edges are incorrectly coloured black:

![image](https://cloud.githubusercontent.com/assets/55406/6018256/81ecd162-abe9-11e4-83fe-ee6508c91360.png)

![image](https://cloud.githubusercontent.com/assets/55406/6018328/edf6ac5c-abe9-11e4-9b4a-c08c8297031e.png)

![image](https://cloud.githubusercontent.com/assets/55406/6018270/93fdd6a8-abe9-11e4-907c-d625d95643a4.png)

Whether an edge (say, A-B) is coloured seems to depend on whether it is added as A-B or B-A.

**Comment by stevenbird** [comment]
A similar problem arises for deleting edges, but not for setting edge width.

**Comment by jarredgallina** [comment]
Seems to be entirely a graphical problem, I'm taking a look now.
