### ISSUE TITLE
Methods to get entries and keys from a dictionary

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#250]
I've added two new dictionary methods (in https://github.com/snapapps/edgy/commit/9e6906a4546cc51d8422500c17f05e8a1a2dcb85 and  https://github.com/snapapps/edgy/commit/188d3d58a2ca38de575bb9ce9e630092de12513b): [entriesInDict](https://github.com/snapapps/edgy/blob/master/edgy/collections.js#L546) and [keysInDict](https://github.com/snapapps/edgy/blob/master/edgy/collections.js#L550). However they don't return anything. @muon would you please advise?

**Comment by Muon** [comment]
They need to be added to the blocks list to actually show up (search for `block('`).

**Comment by stevenbird** [comment]
They do show up. Maybe that was in a separate commit. The problem is they don't return a usable result, just an empty list. I might have to process the return value of Map.keys and Map.elements, not just wrap them with List().

**Comment by Muon** [comment]
Blech, I cannot read. Okay, I think what's happening is that they're returning ES6 iterator objects, which  you need to listify with `Array.from()`, so those should be `Array.from(dict.entries())` and `Array.from(dict.keys())`.

**Comment by stevenbird** [comment]
Thanks @muon.

**Comment by stevenbird** [comment]
@muon – the result of this cannot be used for iteration with `foreach _ in _`.

**Comment by Muon** [comment]
Nono, that was just to turn the iterators into JS arrays! You still need to make them into Snap `List`s.

**Comment by stevenbird** [comment]
Ah, thank you!

**Comment by stevenbird** [comment]
It's implemented [here](https://github.com/snapapps/edgy/blob/master/edgy/collections.js#L547). But this gives me `TypeError: number is not a function`:

![image](https://cloud.githubusercontent.com/assets/55406/6555478/9fdf69e6-c6ba-11e4-9a05-4a6acbf5fd16.png)

**Comment by stevenbird** [comment]
Maybe I need to dereference the Array before calling the List constructor in `List(Array.from(dict.keys()))`

**Comment by stevenbird** [comment]
It turns out that this works fine, closing.
