### ISSUE TITLE
Dictionary saving

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#251]
When a literal dictionary is saved (as a project) then re-opened, it is corrupted: `Dict (1:one,2:two)` becomes `Dict(' ':1,' ':one,' ':2,' ':two)`.

**Comment by stevenbird** [comment]
The result of saving a `Dict(a:1)` is the following XML. Looks like it is missing some structure.

```
<block s="reportNewDict"><list><l>a</l><l>1</l></list></block>
```

**Comment by stevenbird** [comment]
@muon would you please advise?

**Comment by Muon** [comment]
The type needs to be detected in the serialization code (lives in `store.js`, there's a `changesToStore.js` as well, I think), and it needs to be unserialized there as well. You need to create a new XML tag for this.
