### ISSUE TITLE
XML export does not export dictionary values saved in variables.

### ISSUE THREAD

**Issue by gregbreese** [snapapps/edgy#254]
Before exporting the project.
![dict_before_export](https://cloud.githubusercontent.com/assets/5467808/7219038/bdbcb5f0-e6d0-11e4-8125-5a65cba1ef54.PNG)

After importing the project.
![dict_after_export](https://cloud.githubusercontent.com/assets/5467808/7219041/c8185158-e6d0-11e4-9fe9-e70ce06da1bf.PNG)

There is nothing exported into the xml when the export is done.

**Comment by stevenbird** [comment]
@gregbreese – thanks for reporting this issue
