### ISSUE TITLE
Manual layout via blocks

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#260]
When the `x` and `y` coordinates of a node are set, the graph display should be updated accordingly. This may involve switching the global setting to manual layout.

![image](https://cloud.githubusercontent.com/assets/55406/7530749/87035b8e-f591-11e4-9ad3-61759e8da7f9.png)

**Comment by Muon** [comment]
This is supposed to already happen, and seems to work on some tests I've run. (Though the nodes will rearrange themselves if the layout is reshown.) The `fixed` attribute should be used to fix nodes to positions.
