### ISSUE TITLE
Loading exported variables

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#272]
Importing an exported dictionary of dictionaries doesn't work. I'm trying to create a data structure for representing inter-city distances, and then sharing that with students by exporting a dictionary of dictionaries. This might be a more general problem with collection types (or nested collections).

![image](https://cloud.githubusercontent.com/assets/55406/7624072/72b39740-fa26-11e4-91c7-2a4b5374140c.png)

![image](https://cloud.githubusercontent.com/assets/55406/7624098/b176d816-fa26-11e4-8919-f56dc1ca806a.png)

Cf https://github.com/snapapps/edgy/pull/270

**Comment by cyderize** [comment]
The export is fine (i.e. it contains the expected data), but the import seems to be incorrect.

It doesn't help that the way Dict is displayed in the WatcherMorph means you can't see nested dictionaries. I'll try to think of a fix for this.
