### ISSUE TITLE
XSS vulnerability via "JavaScript function" block.

### ISSUE THREAD

**Issue by Pavlos1** [snapapps/edgy#274]
When a user introduces a JavaScript block into an edgy project, that JavaScript code is not sandboxed; it is executed with the same privileges as the JavaScript that runs as part of edgy itself. Notably, JavaScript function blocks can modify document.cookie, localStorage, sessionStorage and call document.write(), etc..

A user can craft a malicious .xml file and send it to a victim. If the victim imports it and runs the JavaScript block, the user can modify and/or delete any edgy-related storage, be it a currently opened project or projects stored in localStorage. Alternatively, they can craft a URL that contains the malicious XML.

Furthermore, depending on how cloud storage is implemented, this attack could also steal cloud storage credentials, or at least session tokens.

I have uploaded an example .xml file (https://drive.google.com/file/d/0B8AoJhc4H8CBeXBfSWhubmNRVlE/view?usp=sharing) that shows the attack in practice. I have tested it both while running edgy locally and from github.io. This file will overwrite all saved project data with "null" when the green flag is pressed. Open file at your own risk and make sure to have backups.

**Comment by stevenbird** [comment]
Thanks for reporting this @Pavlos1. @brianharvey does this vulnerability also exist in Snap?

**Comment by brianharvey** [comment]
I'm sure it does.  It's hard to see how JS Function could fulfill its purpose -- which is to stop people from bugging Jens with pull requests -- unless it allows arbitrary extensions.  I agree that this is a concern; we're sort of thinking we'll ameliorate it by maintaining a library of officially blessed JS extensions and warning people away from third party ones.

**Comment by stevenbird** [comment]
Thanks Brian. I think we will disable it in Edgy, since we're happy to
consider pull requests for the foreseeable future.

**Comment by Pavlos1** [comment]
Could we not just make edgy throw a warning along the lines of "This program is asking for permissions to execute code at a higher privilege. Do you wish to trust it?", and allow the user to choose if they want the JavaScript block to run?

This seems like a better solution until we have proper sandboxing. The JavaScript function block is actually quite helpful, especially for calling functions from Math.* that aren't in the Operators tab.

**Comment by stevenbird** [comment]
I like that solution. Would you be willing to submit a PR?

**Comment by Pavlos1** [comment]
I'll try. It'll take some time to do -- I need to familiarize myself with when Edgy actually calls eval (or whatever else) and how to throw errors, add settings etc.

**Comment by stevenbird** [comment]
A lightweight solution might be to add an option to the settings menu,
unchecked by default: "Allow JavaScript block".
