### ISSUE TITLE
"new graph" and "new digraph" blocks do not reset counter used by "new node"

### ISSUE THREAD

**Issue by ziadmbaroudi** [snapapps/edgy#278]
Using "new node" increments a counter in readiness for the next node to be created. This counter is not reset by "new graph" or "new digraph". A student debugging their program for generating binary trees ends up with node labels starting where the last test left off.

**Comment by stevenbird** [comment]
Thanks @ziadmbaroudi. I agree that the counter should be reset when a new graph is initialised.
