### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#287]
Edgy manipulates a global graph object. However, for testing purposes, it would be good to support the creation of a test suite, for which it would be useful to have a handle for a graph. Then we could write:

```
for G in test_graphs:
    load_graph(G)
    run test suite
```

We could save a graph to a variable as follows:

```
generate_complete_graph_on-5-vertices
K5 = save_graph(G)
```

Useful example graphs could be provided on the network tab, e.g. the Muddy City graph.

**Comment by stevenbird** [comment]
I guess we could represent the graph object as a dictionary:

```
nodes: list of node identifiers
edges: list of edge identifiers
digraph: boolean
node_properties: dict mapping node ids to dicts mapping str keys to arbitrary values
edge_properties: dict mapping edge ids to dicts mapping str keys to arbitrary values
```

**Comment by cyderize** [comment]
Wouldn't it be possible to just use the already available JSON representation as the handle?

**Comment by stevenbird** [comment]
We need to think about avoiding use of the stage (cf pen-down and pen-up in Snap).

**Comment by cyderize** [comment]
I think the following type of design should work well enough (my prototype so far):
![testing](https://cloud.githubusercontent.com/assets/8522468/8389847/ce604e30-1cbd-11e5-817b-aed87d8c6e42.png)

In my opinion the graphs should still be redrawn at each step, as that might actually be useful for some purposes, so you can know what graph is being tested and whatnot. Adding a `hide graph` block at the start will allow the user to stop the graphs from being drawn, and that should be sufficient for the use cases I can think of.

Useful graphs can then be added to the network tab as suggested.

**Comment by stevenbird** [comment]
This is looking good. What would a user see when inspecting a list of saved graphs? I.e. is a saved graph a string, an object reference, or something else?

**Comment by cyderize** [comment]
At the moment it's a string containing the JSON representation of the graph (which is potentially a very long string unfortunately).
![graphs](https://cloud.githubusercontent.com/assets/8522468/8390970/c37bef9a-1cf1-11e5-8895-b87ffea06190.png)

Would it be worth changing this to something more easy to display in a variable watcher?

**Comment by stevenbird** [comment]
This is fine for now, though we might want to think about a more human-readable display in future.

I presume that loading reads those strings, and that a user could edit a graph's JSON string to modify it.

**Comment by cyderize** [comment]
Yes, a user can edit a graph's JSON string to modify it if they wish.

If it becomes necessary, a Map could be used as the handle, which would be more human readable. This would require a conversion between the Map and an Object to occur when saving/loading graphs, but shouldn't be too hard to do.
