### ISSUE TITLE
Undirected edges undetected if named (end, start)

### ISSUE THREAD

**Issue by ziadmbaroudi** [snapapps/edgy#288]
Whether checking edge_exists() or setting colour in an algorithm, an undirected edge has to be referred to as (start, end), where start is the label of the first node used when the edge was created. An algorithm cannot stumble upon an edge and colour it or detect that it exists if a nested for loop ends up naming it (end, start). Eg:
Let say we have created an edge (Sylvia, Brad)
foreach u of all the nodes
   foreach v of all the nodes
      if edge_exists(u, v)
         set dist[u][v] to w(u, v)

edge_exists will return true only when u = Sylvia and v = Brad and not when u = Brad and v = Sylvia.
Given that the edge is undirected, it should be possible to refer to it both ways, right?

**Comment by cyderize** [comment]
I'm pretty sure that in an undirected graph `edge_exists(edge[A,B]) = edge_exists(edge[B,A])` and works as expected...

![ee-g](https://cloud.githubusercontent.com/assets/8522468/8002794/f63d07a0-0bb4-11e5-8d1c-1bb26f035169.PNG)
![ee-1-2](https://cloud.githubusercontent.com/assets/8522468/8002795/f64015a8-0bb4-11e5-958e-a5dd406a0e33.PNG)
![ee-2-1](https://cloud.githubusercontent.com/assets/8522468/8002796/f6442e5e-0bb4-11e5-80fe-3b17b6f93678.PNG)

**Comment by ziadmbaroudi** [comment]
Sorry, I was sure I had struck that issue on several occasions, including the day I added the entry. I just tested it and cyderize was right! Sorry, false alarm!
