### ISSUE TITLE
Permit export of a block sequence

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#293]
Right-clicking a block sequence opens up a menu – this should include the option of exporting the sequence to an XML file.

**Comment by cyderize** [comment]
What should be done when the block sequence contains a custom block?
Should its definition be exported as well?

**Comment by stevenbird** [comment]
What happens when a custom block B1 contains another custom block B2. Does an export of B1 include B2? It seems that it would have to. In general, I think exporting should produce a self-contained result, rather than allowing things to be undefined.

There's a possible problem with loading. If loading would cause an existing custom block to be overwritten, I think there should be a warning message.

**Comment by cyderize** [comment]
Hmm, at the moment, if you export only B1 (using File->Export blocks...) then you don't get B2, and when you try to import B1 (without first defining B2), the B2 block turns into an `obsolete` missing block.

![foo](https://cloud.githubusercontent.com/assets/8522468/8353593/0519408a-1b83-11e5-94ff-0baaca6ea775.png)

This could possibly be a whole new issue. I think exporting should go through dependencies and export them as well.

**Comment by stevenbird** [comment]
+1

**Comment by cyderize** [comment]
Would we want to change the way the current exporting of custom blocks works (to always include all dependencies), and then have similar functionality for exporting block sequences?

If so, I think that we should have another issue open for determining dependencies for exports.

I've also realized that since it's possible to assign a ringified (custom) block to a variable, variable exports may also have dependencies.

**Comment by stevenbird** [comment]
Let's review some use cases, where saving a whole project is unsatisfactory:

1. User U1 wants to share one block B1 (of a set of blocks B1..Bn) with another user U2 who wants to keep their own implementations of B2..Bn. U1 exports B1 and U2 imports it, replacing just their implementation of B1. B1 calls U2's implementation of B2..Bn.

2. Teacher U1 wants to supply the "main program" and student U2's task will be to modify it or implement a block which was defined but left empty by U1. The main program is not a custom block but a sequence of built-in blocks. U2 may have already defined the custom block, and just needs to import the calling program.

Other use cases?

**Comment by cyderize** [comment]
For case 1, the current `Export blocks...` menu is sufficient.

For case 2, adding an `Export` option to block sequences where dependencies are not considered (i.e. the easy way) is sufficient,

There is also a chance that the "main program" from case 2 also requires a custom block that teacher U1 wishes to provide to student U2, in which case the 'easy way' would not be sufficient, as there would be no way to export that block definition along with the block sequence.

In general, I think the current `Export blocks...` menu is okay, but there should be a warning if the user wishes to export a block without also exporting its dependencies (so users don't unsuspectingly give other users blocks that can't be run).

I think adding an `Export...` option to block sequences should also give the user the option to export custom block definitions, although this could be quite clunky. I'm not sure whether that functionality is truly necessary either, as the use case is probably quite rare.

For now, I think the 'easy way' would be okay, unless it becomes apparent that people need extra control.

**Comment by stevenbird** [comment]
I think we cover most of the needed functionality with the simple solution which includes the warning message. If a teacher wants to share a main program and some block definitions, this can be done with two exports. I agree that it would be clunky to try to export a block sequence plus selected custom blocks.
