### ISSUE TITLE
Export warning for custom blocks

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#297]
While testing #296 I exported the following (recursive) custom block as a file [tree.xml](https://gist.github.com/stevenbird/798f224bdbf52f6e12df) using the file menu. When I re-loaded it I could not open or execute it.

![image](https://cloud.githubusercontent.com/assets/55406/8406141/e88b9518-1e9c-11e5-8a87-c9a2fdc8f5cf.png)

**Comment by stevenbird** [comment]
Oh, the problem is that I didn't save `new node`. Shall we warn when exporting custom blocks depend on other blocks that are not being exported?

**Comment by cyderize** [comment]
It is meant to warn for this. I've just realised that the dependency warning doesn't seem to work for reporter blocks (only command blocks). I'll try to figure out what's going on here.
