### ISSUE TITLE
Graph generators

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#300]
Identify any new [NetworkX graph generator functions](https://networkx.github.io/documentation/latest/tutorial/tutorial.html#graph-generators-and-graph-operations) that are are now exposed through the [JSNetworkX API](http://felix-kling.de/JSNetworkX/api_progress.html) and add ones that look interesting.

**Comment by cyderize** [comment]
These generators are now available:

- `emptyGraph` would essentially add `n` nodes to the graph, so it's probably not useful/necessary
- `fullRaryTree` generates a tree of branching factor `r` with `n` nodes - I think this one might be interesting
- `trivialGraph` would essentially add one vertex to the graph, so it's probably not useful/necessary
- `havelHakimiGraph` generates a simple graph with a given degree sequence - this seems quite interesting
- `binomialGraph` binomially generates a graph of `n` vertices with an edge probability `p` - we've used this type of graph generation in algorithmics, so I'd say this one would be quite useful
- `bullGraph` generates a bull graph - probably not that interesting
- `krackhardtKiteGraph` returns the Krackhardt Kite Social Network - not sure how useful this would be
- `makeSmallGraph` and `makeSmallUndirectedGraph` generate graphs from an adjacency list or edge list, but this would probably be quite clunky in edgy
- `davisSouthernWomenGraph` returns the Davis Southern women social network - not sure how useful this would be
- `florentineFamiliesGraph` returns the Florentine families graph - not sure how useful this would be
- `karateClubGraph` returns Zachary's Karate club graph - not sure how useful this would be

I think the `fullRaryTree`, `havelHakimiGraph` and `binomialGraph` generators are the most interesting. Should I include any of the other ones?

**Comment by gregbreese** [comment]
Those three would all be of interest. It would be good to have a generator for some form of scale-free graph such as Barabási–Albert.
