### ISSUE TITLE
ATLAS example

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#301]
Port the [NetworkX Atlas Example](https://networkx.github.io/documentation/latest/examples/drawing/atlas.html) for use in the Edgy Gallery. Can we avoid the need to add support for disjoint union of (saved) graphs?

**Comment by cyderize** [comment]
The atlas example seems to require `graph_atlas_g` which is not implemented by JSNetworkX (yet).

Implementing the function ourselves would be possible, but it's a very large function (1253 graphs, from what I see, although the atlas example only uses the first 208 of them).

**Comment by stevenbird** [comment]
Hmm, how feasible would it be for us to port [graph_atlas_g](http://networkx.lanl.gov/_modules/networkx/generators/atlas.html#graph_atlas_g) ourselves? We could just use Python to dump out all the graphs.

I can think of two approaches:

1. Dump a list of JSON strings and wrap them in our XML block format and put this in the examples directory. Might be too slow to load.
2. Dump in the format used by `load graph from URL`, then add a block to the collections tab `atlas N` which loads the nth graph.

**Comment by stevenbird** [comment]
We've agreed to try the first approach.
