### ISSUE TITLE
Global node attributes

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#304]
Replicate the following blocks on the network tab, so that node and edge properties can be set globally. These properties are applied to the nodes and edges that exist currently, not to new nodes and edges.

![image](https://cloud.githubusercontent.com/assets/55406/8419583/4a779568-1efe-11e5-874e-a8b2e64b6b0b.png)

* `set ATTR of nodes to PROP`
* `set attributes of nodes from DICT`
* `set ATTR of edges to PROP`
* `set attributes of edges from DICT`

**Comment by cyderize** [comment]
Should these be in the network tab?

I would've thought `set ATTR of nodes to PROP` would go into the nodes tab, and similar for the other ones.
