### ISSUE TITLE
Update JSNetworkX to latest version

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#306]
From what I can tell, issue #300 depends on the updated JSNetworkX API.

This requires us to update all the graph code to use the new API.
Unfortunately this is quite a hard task as many things have changed (every function name has changed from snake_case to camelCase, and there have been other changes as well).

**Comment by stevenbird** [comment]
Thanks for pointing this out @cyderize. I'd prefer to wait til the summer to do this, unless there's any more pressing reasons to do the update.
