### ISSUE TITLE
Node position saving

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#321]
At the moment, the saving of node positions is rather confusing.

In order to have the positions of nodes saved, the user must set the `fixed` attribute to true for the nodes, and then set the `x` and `y` attributes of the nodes. Moving the nodes manually has no effect on the saved positions.

This is confusing because:
- A user who chooses 'manual layout' may expect the node positions to be saved, but they aren't (and neither is the manual layout option).
- A user who sets `fixed` to true, sets the `x` and `y` attributes the nodes, and then moves them manually will get unexpected saved positions (they'll just be the last `x` and `y` attributes set, not their new positions).
- A user who sets `fixed` to true and then moves the nodes manually will have no positions saved at all.

I think the following should be done:
- Save the layout mode as part of the project - so when you select 'manual layout', it'll be on manual layout when you reload the project.
- When in either manual layout mode or if the nodes are fixed, record the actual positions of the nodes when saving, not just the ones set using the blocks.

**Comment by stevenbird** [comment]
+1
