### ISSUE TITLE
Graph layout menu options

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#322]
~~I think the layout options in the menu should read~~
- ~~WebCola constraint-based layout~~
- ~~WebCola with downward edges~~
- ~~D3 force directed layout~~
- ~~Manual Layout~~

~~Where only one of these can be ticked at a time. At the moment, you can have multiple ticked - I can tick 'manual' and 'force-directed' at the same time, which makes no sense.~~

EDIT: As @Muon pointed out, you can validly combine options, however I think the downward edges option should only be available when webcola is being used.

**Comment by Muon** [comment]
When you have both on, IIRC that means the default layout is force-based, but nodes lock position when you drag.

**Comment by cyderize** [comment]
Ah yeah, that's right. So manual layout can be combined with the other options, which makes sense (although it's a bit confusing).

Downward edges don't work with force layout though, since that needs WebCola. We should probably disable that option when force layout is chosen
