### ISSUE TITLE
Update block documentation

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#330]
Some recently added blocks lack help documentation (see [help](https://github.com/snapapps/edgy/tree/master/help) and [help source](https://github.com/snapapps/edgy/tree/master/help%20source)).

In some cases, we just need to modify existing documentation, e.g. the help documentation for `set ATTR of node N to A` can be extended to mention `set ATTR of all nodes to A`, and then this same documentation can be referenced from the new block.

In other cases, new documentation may be required.

Steps:
1. identify the Edgy-specific blocks needing documentation
2. draft the documentation in any convenient format
3. after feedback, produce the documentation images

**Comment by cyderize** [comment]
Mostly for my own reference, these blocks need documentation (quite a lot of blocks need documentation actually):

Network
- `show`
- `show subgraph from node _ of depth _`
- `hide`
- `save graph`
- `load graph _`

Nodes
- `node _ exists`
- `set _ of all nodes to _`
- `set attributes of all nodes from _`
- `display node attribute _`
- `hide node attribute`
- `is _ displayed`
- `hide _ in subgraph`

Edges
- `edge _ exists`
- `set _ of all edges to _`
- `set attributes of all edges from _`
- `display edge attribute _` 
- `show _ in subgraph`
- `hide _ in subgraph`

Collections
- need documentation for all blocks

Control
- `for each item of _`
- `for i = _ to _` (documentation already exists, but is not linked to the block yet)
- `when node _ double-clicked`

**Comment by stevenbird** [comment]
Let's try to group them, and share documentation images across multiple
blocks.

Eg node-exists and edge-exists could be documented together.

**Comment by cyderize** [comment]
This is mostly done now, I'm just going to do a new draft of some of the collections blocks to add better examples..
