### ISSUE TITLE
Saved block sequences omit variables

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#345]
The gallery page includes an example for Dijkstra's algorithm. When I import it to Edgy, the `start_node` variable defined in the code does not exist as a variable in the Variables tab.

http://www.snap-apps.org/edgy.html

**Comment by cyderize** [comment]
Custom block exports also leave out global variables. Should that be changed as well?

**Comment by stevenbird** [comment]
Right. It should be possible to import these saved materials and have them behave properly. One step we already do is look for dependent blocks and export those as well. Identifying any global variables is a similar case, i.e. a name defined in the surrounding context that is required by a custom block or block sequence.

**Comment by cyderize** [comment]
So export blocks should be extended to also allow exporting of global variables (probably using a checkbox like for attributes)

Looking at the Dijkstra example, we'd also have to export node attributes along with the block sequence and global variables for it to work. At the moment all we do is warn if custom blocks are used (and if they are, we still don't export them). 

I think the user should be given the option to export the dependencies - for example, we check for custom blocks, global variables, and node/edge attributes; if any are found we show a dialog with checkboxes allowing the dependencies to be exported.

**Comment by stevenbird** [comment]
Let's hold off on this for now.
