### ISSUE TITLE
Maths blocks

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#347]
In Algorithmics, I have often found the need for a `max(n1, n2, ...)` and `min(n1, n2, ...)` as well as an infinity constant and a `raise x to power y`. All of these are available in JavaScript (in fact the string `Infinity` gets parsed as a floating point infinity already), so it should not be hard to add these.

**Comment by stevenbird** [comment]
It would be great to have these, please go ahead. Variables tab?

**Comment by cyderize** [comment]
I was thinking the operators tab, since that's where most of the other mathematical things seem to lie.
