### ISSUE TITLE
Behaviour of edge labels

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#359]
The display edge attribute block doesn't really work in the way one would expect it to.
For example, if you set the color of an edge to 'red', and the display the edge attribute 'color', it works correctly. But if you then set the color of the edge to 'blue', the displayed text doesn't change. In addition, setting the label of an edge will always cause the displayed text to change, even if you're trying to display a different attribute. Default values aren't displayed either.

I think this should be made similar to the way node attributes are displayed.

**Comment by stevenbird** [comment]
+1
