### ISSUE TITLE
Issue with project downloads

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#368]
Georgia Gouros reports the following problem downloading a project in Edgy:

https://support.google.com/webmasters/answer/3258249

**Comment by stevenbird** [comment]
![image 1](https://cloud.githubusercontent.com/assets/55406/12131777/ac97e8c8-b469-11e5-939f-ac363062b713.png)

**Comment by cyderize** [comment]
Updating Snap! (#320) will fix this issue I believe - I'm still working on it
