### ISSUE TITLE
Separate Edgy code from Snap! code

### ISSUE THREAD

**Issue by cyderize** [snapapps/edgy#370]
At the moment we have some files from Snap! that have changes made by us for use in Edgy (e.g. `store.js`, `gui.js`, `byob.js`, `blocks.js`). I think it would be a good idea to find all of these and move them into the change-set files (`changesToBlah.js`) because that would mean we could use an unmodified Snap! snapshot and it'd be easier to update to new Snap! versions in the future.

Also, if Snap! comes out with a new extensible architecture, we'd probably end up having to do this anyway, so I think doing this at some point would be worthwhile.

**Comment by stevenbird** [comment]
We'll do this work in a new branch, with the intention of deploying during the mid-year break.

**Comment by stevenbird** [comment]
@cyderize: let's ask for input from the snap-modders group.
