### ISSUE TITLE
Problem saving blocks

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#396]
Georgia Gouros reports the error: `Save failed: TypeError: Cannot read property 'element' of null`

![image](https://cloud.githubusercontent.com/assets/55406/13732585/28ad1f1e-e9da-11e5-845c-94588d238bc3.png)

**Comment by cyderize** [comment]
I think this is due to an issue with priority queue serialization.

I'll submit a PR fixing it in a little bit.

**Comment by stevenbird** [comment]
Thanks for the quick fix @cyderize
