### ISSUE TITLE
Hamiltonian circuit with backtracking search

### ISSUE THREAD

**Issue by stevenbird** [snapapps/edgy#404]
There is a backtracking algorithm that explores all possible hamiltonian paths by using DFS on a decision tree (this tree is just the call graph of the algorithm, it is not instantiated):

![image](https://cloud.githubusercontent.com/assets/55406/14417133/edb177c6-fff4-11e5-80bd-ce42880a919c.png)

Please create a new Edgy example for this algorithm.

**Comment by stevenbird** [comment]
Thanks @cyderize. I'd like to refine this a little, making less use of global variables. Could the current node and the path so far be make formal parameters for the block? I think it's fine to accumulate the results in a global variable.

**Comment by cyderize** [comment]
Yes, that would make a lot of sense to do.

I'll open a new PR with a revised example.

**Comment by stevenbird** [comment]
Actually, the result list works as a third parameter too, and this is probably cleanest.

**Comment by stevenbird** [comment]
Closed by #413.
