### ISSUE TITLE
"When node node double clicked" block doesnt work

### ISSUE THREAD

**Issue by arceusawsom1** [snapapps/edgy#431]
I get an "Uncaught typeError: cannot read property "pushcontext" of undefined
It's not my fault because even if i use the "sim" example program it still happens

**Comment by arceusawsom1** [comment]
That was in chrome, i just tried firefox and i get a different error
"TypeError: Proc undefined"
also in both instances if i use the "node" block it will do a little error message saying that node is undefined

**Comment by stevenbird** [comment]
@arceusawsom1 thanks for the report.
@cyderize: are you able to replicate this?
