### ISSUE TITLE
Edgy calling external Javascript has a permission problem

### ISSUE THREAD

**Issue by GeorgiaG007** [snapapps/edgy#433]
when executing Edgy code error results as shown in image
![image](https://cloud.githubusercontent.com/assets/26209779/23593352/eb6608ae-0261-11e7-9901-4b2e3c64d16e.png)

**Comment by Dalordish** [comment]
This is because you are trying to execute a javascript function without enabling full Execution privileges, found here.
![image](https://cloud.githubusercontent.com/assets/5959205/23600497/f0e7b1c2-029a-11e7-9ccd-e841c44fac96.png)

**Comment by GeorgiaG007** [comment]
Thanks Richard

**Comment by stevenbird** [comment]
Thanks @Dalordish
