### ISSUE TITLE
Deleting speech bubble removes edgy based blocks

### ISSUE THREAD

**Issue by Hazelfire** [snapapps/edgy#436]
When deleting a speech bubble created with the say block, all edgy based blocks are removed from the editor, needing a reload to get the blocks back.

I'll try and work on a fix on my fork of the project.

**Comment by Hazelfire** [comment]
My apologies, this is an issue with snap, not edgy.

**Comment by stevenbird** [comment]
Thanks @Hazelfire – hope you found the right place to report it.
