### ISSUE TITLE
Please increase the permitted graph nodes to > 512 limit,  1024 would be good!

### ISSUE THREAD

**Issue by GeorgiaG007** [snapapps/edgy#444]
is it possible to increase the number of nodes to a higher limit, current limit is 150????, could that be increased?

**Comment by soxfox42** [comment]
Yes, it is possible. Under the options menu, the first item is "Maximum visible nodes." This should allow up to 1000, however do be warned that on slower machines many nodes can cause Edgy to freeze. Hopefully this is still helpful, 2 years later.

**Comment by GeorgiaG007** [comment]
Thanks for your research Finn. Edgy is still useful this year for getting you all University ready, still ticking along.
Cheers
Georgia
